- Rizaldi/ReadMe.txt.txt
tambah teks di file readme rizaldi
> adding text on readme file

- Arief/ReadMe.txt
- LOG/LOGAPN-30April2018.txt
> LOGAPN-30April2018.txt

- LOG/LOGRCH-30April2018.txt
- Richa/27-04-2018/CreatingVariables.java
- Richa/27-04-2018/EscapeSequencesComments.java
- Richa/27-04-2018/Ex2Drills1.java
- Richa/27-04-2018/Ex2Drills2.java
- Richa/27-04-2018/Ex3Drills1.java
- Richa/27-04-2018/Ex4Drills2.java
- Richa/27-04-2018/Ex5Drills1.java
- Richa/27-04-2018/Ex5Drills2.java
- Richa/27-04-2018/Ex6Drills1.java
- Richa/27-04-2018/Ex6Drills2.java
- Richa/27-04-2018/FirstProg.java
- Richa/27-04-2018/GasolineReceipt.java
- Richa/27-04-2018/MathOperations.java
- Richa/27-04-2018/PrintingChoices.java
- Richa/30-04-2018/RichaFitria.java
-CreatingVariables
-EscapeSequencesComments
-MathOperation
-GasolineReceipt
-PrintingChoices
-FirstProg
-Exercise 2 Drills 1
-Exercise 2 Drills 2
-Exercise 3 Drills 1
-Exercise 4 Drills 2
-Exercise 5 Drills 1
-Exercise 5 Drills 2
-Exercise 6 Drills 1
-Exercise 6 Drills 2
-RichaFitria: Tugas apa saja yang membuat saya senang, marah dan menyesal
> LOGRCH-30April2018

- Andrian/27April18/CreatingVariables.java
- Andrian/27April18/EscapeSequenceComments.java
- Andrian/27April18/Ex1Drills1.java
- Andrian/27April18/Ex1Drills2.java
- Andrian/27April18/Ex2Drills1.java
- Andrian/27April18/Ex2Drills2.java
- Andrian/27April18/Ex3Drills1.java
- Andrian/27April18/Ex4Drills2.java
- Andrian/27April18/Ex5Drills1.java
- Andrian/27April18/Ex5Drills2.java
- Andrian/27April18/Ex5Drills3.java
- Andrian/27April18/Ex6Drills1.java
- Andrian/27April18/Ex6Drills2.java
- Andrian/27April18/Ex6Drills3.java
- Andrian/27April18/FirstProg.java
- Andrian/27April18/GasolineReceipt.java
- Andrian/27April18/MathOperations.java
- Andrian/27April18/PrintingChoises.java
- Andrian/30April18/TugasKemarin.java
- LOG/LOGANDR-30April2018.txt
>Menambahkan subfolder pada foler Andrian:
27April2018
30April2018
>Menambahkan file :
- CreatingVariable.java
- EscapeSequenceComments.java
- Ex1Drills1.java
- Ex1Drills2.java
- Ex2Drills1.java
- Ex2Drills2.java
- Ex3Drills1.java
- Ex3Drills2.java
- Ex4Drills2.java
- Ex5Drills1.java
- Ex5Drills2.java
- Ex5Drills3.java
- Ex6Drills1.java
- Ex6Drills2.java
- FirstProg.java
- GasolineReceipt.java
- MathOperation.java
- PrintingChoises.java
- TugasKemarin.java
> LOGANDR-30April2018

- LOG/LOGKA-30April2018.txt
> LOGKA-30April2018

- Arief/Tugas270418.java
- LOG/LOGAPN-30April2018-2.txt
> LOGAPN-30April2018-2

- LOG/LOGANDR-30April2018-1.txt
> LOGANDR-30April2018-1

- LOG/LOGANDR-30April2018-2.txt
- Tugas/Soal Latihan/SoalCeritaTugas30April18-rifanandrian.txt
- Tugas/Soal Latihan/Tugas-30April18-SoalCerita-rifanandrian.txt
>Menambahkan file :
- SoalCeritaTugas30April18-rifanandrian.txt pada folder ..\BootCampG7\Tugas\Soal lathian\
> LOGANDR-30April2018-2

- Andrian/1May2018/Alifhar1.java
- Andrian/1May2018/Alifhar2.java
- Andrian/1May2018/Alifhar3.java
- Andrian/1May2018/Andrian1.java
- Andrian/1May2018/Andrian2.java
- Andrian/1May2018/Andrian3.java
- Andrian/1May2018/Arif1.java
- Andrian/1May2018/Arif2.java
- Andrian/1May2018/Arif3.java
- Andrian/1May2018/Khairil1.java
- Andrian/1May2018/Khairil2.java
- Andrian/1May2018/Khairil3.java
- Andrian/1May2018/Richa1.java
- Andrian/1May2018/Richa2.java
- Andrian/1May2018/Richa3.java
- Andrian/1May2018/Rizaldi1.java
- Andrian/1May2018/Rizaldi2.java
- Andrian/1May2018/Rizaldi3.java
- Andrian/1May2018/Tugas1.java
- Andrian/1May2018/Tugas2.java
- Andrian/1May2018/Yana1.java
- Andrian/1May2018/Yana2.java
- Andrian/1May2018/Yana3.java
- LOG/LOGANDR-1May2018.txt
Adding file in sub folder Andrian 
Adding Excercise math operation from kang henra and G7
> LOGANDR-1May2018

- Richa/01-05-2018/Alifhar1.java
- Richa/01-05-2018/Alifhar2.java
- Richa/01-05-2018/Alifhar3.java
- Richa/01-05-2018/Andrian1.java
- Richa/01-05-2018/Andrian2.java
- Richa/01-05-2018/Andrian3.java
- Richa/01-05-2018/Arief1.java
- Richa/01-05-2018/Arief2.java
- Richa/01-05-2018/Arief3.java
- Richa/01-05-2018/Khairil1.java
- Richa/01-05-2018/Khairil2.java
- Richa/01-05-2018/Khairil3.java
- Richa/01-05-2018/Rizaldi1.java
- Richa/01-05-2018/Rizaldi2.java
- Richa/01-05-2018/Rizaldi3.java
- Richa/01-05-2018/SoalLatihanHendra.java
- Richa/01-05-2018/SoalLatihanHendra2.java
- Richa/01-05-2018/Yana1.java
- Richa/01-05-2018/Yana2.java
- Richa/01-05-2018/Yana3.java
2 soal latihan dari mas hendra
3 soal latihan dari anggota G7 kecuali punya Richa
total soal yang dikerjakan sebanyak 20
> Soal latihan 20 file

- LOG/LOGRCH-1Mei2018-3.txt
- LOG/Soal latihan 20 file.txt
- Richa/01-05-2018/Richa1.java
- Richa/01-05-2018/Richa2.java
- Richa/01-05-2018/Richa3.java
3 Soal Latihan matematika milik saya sendiri
> LOGRCH-1Mei2018-3

- LOG/LOGRCH-2Mei2018-2.txt
- LOG/LOGRCH-2Mei2018.txt
- Richa/02-05-2018/BMIcalculator.java
- Richa/02-05-2018/Ex11Drills1.java
- Richa/02-05-2018/Ex11Drills2.java
- Richa/02-05-2018/Ex7Drills1&2.java
- Richa/02-05-2018/Ex7Drills1dan2.java
- Richa/02-05-2018/Ex8Drills123dan4.java
- Richa/02-05-2018/Ex9Drills1.java
- Richa/02-05-2018/Ex9Drills2.java
- Richa/02-05-2018/Ex9Drills3.java
- Richa/02-05-2018/ForgetfulMachine.java
- Richa/02-05-2018/Khairil2.java
- Richa/02-05-2018/Khairil3.java
- Richa/02-05-2018/RudeQuestions.java
- Richa/02-05-2018/Sequencing.java
- Richa/02-05-2018/VariableChangeShortcuts.java
- Richa/02-05-2018/Yana1.java
perbaikan soal latihan
-Yana1.java
-Khairil2.java
-Khairil 3.java
> LOGRCH-2Mei2018

- LOG/LOGRCH-3Mei2018.txt
- Richa/03-05-2018/Ex14Drills2.java
- Richa/03-05-2018/Ex14Drills3.java
- Richa/03-05-2018/Ex14Drills4.java
-Exercise 14 Drills 2
-Exercise 14 Drills 3
-Exercise 14 Drills 4
> LOGRCH-3Mei2018

- LOG/LOGRCH-3Mei2018-2.txt
- Tugas/TugasLatihan/Richa/LatihanBoolean1.java
- Tugas/TugasLatihan/Richa/LatihanBoolean2.java
- Tugas/TugasLatihan/Richa/LatihanBoolean3.java
- Tugas/TugasLatihan/Richa/LatihanBoolean4.java
-LatihanBoolean1.java
-LatihanBoolean2.java
-LatihanBoolean3.java
-LatihanBoolean4.java
> LOGRCH-3Mei2018-2

- LOG/LOGANDR-3May2018-1.txt
- LOG/LOGANDR-3May2018.txt
- Tugas/TugasLatihan/Andrian/TugasBoolean1.java
- Tugas/TugasLatihan/Andrian/TugasBoolean2.java
- Tugas/TugasLatihan/Andrian/TugasBoolean3.java
- Tugas/TugasLatihan/Andrian/TugasBoolean4.java
Menambahkan file :
- tugasbolean 1-4 pada sub folder tugas\TugasLatihan\Andrian
> LOGANDR-3May2018-1

- LOG/LOGYNY-03Mei2018-3.txt
- Tugas/Soal Latihan/Yana/Yana-SoalBoolean.txt
nama LOG seharusnya LOGYNY-03Mei2018-3
file LOGYNY-03Mei2018-3.txt
> LOGYNY-03Mei2018

- LOG/LOGRCH-3Mei2018-3.txt
- Tugas/Soal Latihan/Richa/RichaBoolean.txt
> LOGRCH-3Mei2018-3

- LOG/LOGRCH-3Mei2018-4.txt
- Richa/03-05-2018/Ex14Drills1.java
- Richa/03-05-2018/ShallowGrandmother.java
- Richa/03-05-2018/WeaselOrNot.java
> LOGRCH-3Mei2018-4

- LOG/LOGRCH-4Mei2018.txt
- Richa/04-05-2018/AlifharBoolean1.java
- Richa/04-05-2018/AlifharBoolean2.java
- Richa/04-05-2018/AlifharBoolean3.java
- Richa/04-05-2018/AndrianBoolean1.java
- Richa/04-05-2018/AndrianBoolean2.java
- Richa/04-05-2018/AndrianBoolean3.java
- Richa/04-05-2018/AriefBoolean1.java
- Richa/04-05-2018/AriefBoolean2.java
- Richa/04-05-2018/AriefBoolean3.java
- Richa/04-05-2018/KhairilBoolean1.java
- Richa/04-05-2018/KhairilBoolean2.java
- Richa/04-05-2018/KhairilBoolean3.java
- Richa/04-05-2018/RichaBoolean1.java
- Richa/04-05-2018/RichaBoolean2.java
- Richa/04-05-2018/RichaBoolean3.java
- Richa/04-05-2018/RizaldiBoolean1.java
- Richa/04-05-2018/RizaldiBoolean2.java
- Richa/04-05-2018/RizaldiBoolean3.java
- Richa/04-05-2018/YanaBoolean1.java
- Richa/04-05-2018/YanaBoolean2.java
- Richa/04-05-2018/YanaBoolean3.java
Soal boolean semua anggota G7 masing-masing 3 soal
termasuk hasil koreksi
> LOGRCH-4Mei2018

- Andrian/4May2018/TugasBooleanAlifhar1.java
- Andrian/4May2018/TugasBooleanAlifhar3.java
- Andrian/4May2018/TugasBooleanArif3.java
- Andrian/4May2018/TugasBooleanKhairil1.java
- Andrian/4May2018/TugasBooleanRicha2.java
- Andrian/4May2018/TugasBooleanRicha3.java
- Andrian/4May2018/TugasBooleanRizaldi3.java
- Andrian/4May2018/TugasBooleanYana1.java
- Andrian/4May2018/TugasBooleanYana2.java
- LOG/LOGANDR-4May2018.txt
Menambahkan folder :
- 4May2018
Menambahkan file :
- TugasBooleanAlifhar1
- TugasBooleanAlifhar3
- TugasBooleanArif3
- TugasBooleanKhairil1
- TugasBooleanRicha2
- TugasBooleanRicha3
- TugasBooleanRizaldi1
- TugasBooleanYana1
- TugasBooleanYana2
> LOGANDR-4May2018

- Andrian/15May2018/TugasIfAlifhar1.java
- Andrian/15May2018/TugasIfAlifhar3.java
- Andrian/15May2018/TugasIfAndrian1.java
- Andrian/15May2018/TugasIfAndrian2.java
- Andrian/15May2018/TugasIfAndrian3.java
- Andrian/15May2018/TugasIfArif1.java
- Andrian/15May2018/TugasIfArif2.java
- Andrian/15May2018/TugasIfChaudary1.java
- Andrian/15May2018/TugasIfChaudary3.java
- Andrian/15May2018/TugasIfMalik1.java
- Andrian/15May2018/TugasIfMalik2.java
- Andrian/15May2018/TugasIfRicha1.java
- Andrian/15May2018/TugasIfRicha3.java
- LOG/LOGANDR-15May2018-1.txt
Menambahkan sub folder:
15May2018
Andrian/15May2018/TugasIfAlifhar1.java
Andrian/15May2018/TugasIfAlifhar3.java
Andrian/15May2018/TugasIfAndrian1.java
Andrian/15May2018/TugasIfAndrian2.java
Andrian/15May2018/TugasIfAndrian3.java
Andrian/15May2018/TugasIfArif1.java
Andrian/15May2018/TugasIfArif2.java
Andrian/15May2018/TugasIfChaudary1.java
Andrian/15May2018/TugasIfChaudary3.java
Andrian/15May2018/TugasIfMalik1.java
Andrian/15May2018/TugasIfMalik2.java
ndrian/15May2018/TugasIfRicha1.java
Andrian/15May2018/TugasIfRicha3.java
LOG/LOGANDR-15May2018-1.txt
> LOGANDR-15May2018-1

- Andrian/16May2018/TugasIfRizald1.java
- Andrian/16May2018/TugasIfRizaldi2.java
- Andrian/16May2018/TugasIfRyan1.java
- Andrian/16May2018/TugasIfRyan3.java
- Andrian/16May2018/TugasIfVikry1.java
- Andrian/16May2018/TugasIfVikry2.java
- Andrian/16May2018/TugasIfYana1.java
- LOG/LOGANDR-16May2018.txt
Menambahkan sub folder:
16May2018
Andrian/16May2018/TugasIfRizaldi1.java
Andrian/16May2018/TugasIfRizaldi2.java
Andrian/16May2018/TugasIfRyan1.java
Andrian/16May2018/TugasIfRyan3.java
Andrian/16May2018/TugasIfVikry1.java
Andrian/16May2018/TugasIfVikry2.java
Andrian/16May2018/TugasIfYana1.java
LOG/LOGANDR-16May2018.txt
> LOGANDR-16May2018

- LOG/LOGANDR-16May2018-1.txt
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasFor.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasFor1.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForDotSeparatingWord.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForEvenNumber.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForGuessingGame1.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForGuessingGame2.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForHPFensui.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForOddNumber.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForRepeatingWord.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForSeparatingWord.java
- Tugas/TugasLatihan/Andrian/LatihanFor/TugasForStartingNumber.java
+Menambahkan sub folder pada TugasLatuhan/Andrian/LatihanFor
+	LatihanFor
+
+Menambahkan file :
+	TugasFor
+	tugasFor
+	TugasForDotseparation
+	TugasForEvenNumber
+	TugasForOddNumber
+	TugasForGuessingGame1
+	TugasForGuessingGame2
+	TugasForHPFengsui
+	TugasForRepeatingword
+	TugasForSeperatingWord
+	TugasForStartingNumber
> LOGANDR-16May2018-1

- Andrian/18May2018/CountingFor.java
- LOG/LOGANDR-18May2018.txt
- Tugas/TugasLatihan/Andrian/LatihanFor/PrFor1.java
- Tugas/TugasLatihan/Andrian/LatihanFor/PrFor2.java
- Tugas/TugasLatihan/Andrian/LatihanFor/PrFor3.java
- Tugas/TugasLatihan/Andrian/LatihanWhile/PigDiceGame.java
- Tugas/TugasLatihan/Andrian/LatihanWhile/TugasForGuessingGame2.java
- Tugas/TugasLatihan/Andrian/LatihanWhile/TugasWhile1.java
- Tugas/TugasLatihan/Andrian/LatihanWhile/TugasWhile2.java
- Tugas/TugasLatihan/Andrian/LatihanWhile/TugaswhileGuessingGame1.java
Menambahkan sub folder pada TugasLatuhan/Andrian/
LatihanWhile
Menambahkan file :
PigDiceGame
TugasWhileGuessingGame2
TugasWhileGuessingGame2
TugasWhile1
TugasWhile2
PrFor1
Prfor2
Prfor3
> LOGANDR-18May2018
